//
//  DB.swift
//  35. Emoji Riddler
//
//  Created by Despo on 29.12.24.
//

public let movieNames = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "Pulp Fiction",
  "The Lord of the Rings: The Return of the King",
  "Forrest Gump",
  "Inception",
  "The Matrix",
  "Fight Club",
  "The Empire Strikes Back",
  "The Godfather: Part II",
  "The Dark Knight Rises",
  "Schindler's List",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Star Wars",
  "The Good, the Bad and the Ugly",
  "The Lord of the Rings: The Two Towers",
  "Casablanca",
  "Pulp Fiction",
  "The Silence of the Lambs",
  "Seven Samurai",
  "City of God",
  "The Usual Suspects",
  "Léon: The Professional",
  "Spirited Away",
  "The Lion King",
  "The Green Mile",
  "The Departed",
  "Whiplash",
  "Gladiator",
  "Interstellar",
  "The Prestige",
  "The Revenant",
  "Shutter Island",
  "Memento",
  "Goodfellas",
  "The Shining",
  "The Dark Knight Returns",
  "La La Land",
  "Avatar",
  "Titanic",
  "The Avengers",
  "Jaws",
  "A Clockwork Orange",
  "2001: A Space Odyssey",
  "The Terminator",
  "The Social Network",
  "The Big Lebowski",
  "The Intouchables",
  "American History X"
]

public let booksArray = [
    "To Kill a Mockingbird",
    "1984",
    "The Great Gatsby",
    "Pride and Prejudice",
    "The Catcher in the Rye",
    "Moby-Dick",
    "War and Peace",
    "Crime and Punishment",
    "The Odyssey",
    "Brave New World",
    "The Lord of the Rings",
    "The Hobbit",
    "Anna Karenina",
    "Don Quixote",
    "Ulysses",
    "The Brothers Karamazov",
    "Frankenstein",
    "Wuthering Heights",
    "The Picture of Dorian Gray",
    "The Grapes of Wrath",
    "Jane Eyre",
    "The Scarlet Letter",
    "Catch-22",
    "The Kite Runner",
    "The Hunger Games",
    "Harry Potter and the Sorcerer's Stone",
    "The Chronicles of Narnia",
    "The Handmaid's Tale",
    "The Fault in Our Stars",
    "A Tale of Two Cities",
    "Fahrenheit 451",
    "The Secret Garden",
    "Little Women",
    "The Shining",
    "Rebecca",
    "The Great Expectations",
    "Lord of the Flies",
    "The Outsiders",
    "Beloved",
    "Slaughterhouse-Five",
    "Gone with the Wind",
    "The Color Purple",
    "The Road",
    "The Help",
    "The Old Man and the Sea",
    "The Girl on the Train",
    "Shogun",
    "The Night Circus",
    "One Hundred Years of Solitude",
    "The Alchemist"
]


public let animeArray = [
    "Naruto",
    "Attack on Titan",
    "One Piece",
    "Dragon Ball Z",
    "My Hero Academia",
    "Demon Slayer",
    "Death Note",
    "Fullmetal Alchemist: Brotherhood",
    "Sword Art Online",
    "Bleach",
    "Tokyo Ghoul",
    "One Punch Man",
    "Hunter x Hunter",
    "Naruto Shippuden",
    "Neon Genesis Evangelion",
    "Dragon Ball Super",
    "JoJo's Bizarre Adventure",
    "The Promised Neverland",
    "Fruits Basket",
    "Your Name",
    "Cowboy Bebop",
    "Steins;Gate",
    "Attack on Titan: The Final Season",
    "Re:Zero - Starting Life in Another World",
    "Mob Psycho 100",
    "Black Clover",
    "Trigun",
    "Psycho-Pass",
    "Code Geass",
    "Akira",
    "Inuyasha",
    "Yu Yu Hakusho",
    "Digimon Adventure",
    "Fairy Tail",
    "Hellsing",
    "Bleach: Thousand-Year Blood War",
    "Angel Beats!",
    "Death Parade",
    "Clannad",
    "Vinland Saga",
    "Kaguya-sama: Love is War",
    "Cowboy Bebop: The Movie",
    "Made in Abyss",
    "Monogatari Series",
    "Mob Psycho 100 II",
    "Attack on Titan: Season 3",
    "The Rising of the Shield Hero",
    "Parasyte: The Maxim",
    "Sword Art Online: Alicization",
    "March Comes in Like a Lion"
]
